version: '2'
services:
  jenkins:
    image: istresearch/jenkins:latest
    container_name: jenkins
    user: jenkins
    volumes:
      - /data/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      JENKINS_HOST_HOME: "/data/jenkins"
    ports:
      - "8080:8080"
      - "5000:5000"
      - "50000:50000"
